### ISSUE TITLE
Issue for rendering video and images

### ISSUE THREAD

**Issue by FavorMylikes** [meyerls/FruitNeRF#25]
I tried both images and video formats, but they all got the None error below.

The command that I used.
````
ns-render camera-path --output-format images --load-config outputs/images_processed/fruit_nerf/2024-10-05_045546/config.yml --camera-path-filename images_processed/camera_paths/2024-10-05_045546.json --output-path renders/images_ali_20240529_processed/2024-10-05_045546
```

```log
Traceback (most recent call last):
  File "/usr/local/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/render.py", line 530, in entrypoint
    tyro.cli(Commands).main()
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/render.py", line 363, in main
    _render_trajectory_video(
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/render.py", line 140, in _render_trajectory_video
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/content/FruitNeRF/fruit_nerf/fruit_nerf.py", line 313, in forward
    fruit_nerf_output = self.get_inference_outputs(ray_bundle, True)
  File "/content/FruitNeRF/fruit_nerf/fruit_nerf.py", line 227, in get_inference_outputs
    ray_samples = self.proposal_sampler(ray_bundle)
TypeError: 'NoneType' object is not callable
```

**Comment by meyerls** [comment]
This should be fixed in my latest commits inside [dev branch ](https://github.com/meyerls/FruitNeRF/tree/dev)

I have not added any information about multi model rendering. So if you add ``` --rendered-output-names rgb semantics semantics_colormap``` you can render all modalities at once
