### ISSUE TITLE
AttributeError: 'Trimesh' object has no attribute 'as_open3d'

### ISSUE THREAD

**Issue by MisuZeng** [meyerls/FruitNeRF#26]
Hello, I encountered the following error while running run_cluster. py.

Traceback (most recent call last):
  File "clustering/run_clustering.py", line 99, in <module>
    clustering = Clustering(remove_outliers_nb_points=Baum['remove_outliers_nb_points'],
  File "clustering/run_clustering.py", line 51, in __init__
    self.fruit_alpha_shape = self.fruit_alpha_shape_.as_open3d.sample_points_uniformly(1000)
AttributeError: 'Trimesh' object has no attribute 'as_open3d'

Before this, I had already configured the template path and was able to open .clustering/apple_template. ply. 
This issue seems to be caused by the self.fruit_alpha.shape_=alphashape.alphashape (np. asarray (self.fruit_template. points), 10) returns a trimesh object, and the printed result is<trimesh Trimesh (vertices. shape=(1211,3), faces. shape=(2418,3))>, may I ask if this output meets expectations?
Also, I couldn't find as_open3d in the project. Is this a custom method ? It doesn't seem to be included in the trimesh or alphashape libraries.
Could you please help me solve the problem? Thank you so much!

**Comment by liuyi0316** [comment]
did you solve?

**Comment by MisuZeng** [comment]
Yes, I have already solved.

**Comment by ikun-667** [comment]
@MisuZeng How did solve this error?
AttributeError: 'Trimesh' object has no attribute 'as_open3d'

**Comment by meyerls** [comment]
@MisuZeng how did you solve the problem?

Otherwise please refer to issue #21
