### ISSUE TITLE
ns-export-semantics semantic-pointcloud in ns-1.1.4 Error due to

### ISSUE THREAD

**Issue by mitsuki05** [meyerls/FruitNeRF#34]
I created the nerfstudio environment in docker using docker pull ghcr.io/nerfstudio-project/nerfstudio:latest and the FruitNeRF environment using the ns-1.1.4 branch.
After that, pointclouding by ns-train fruit_nerf command was successful, but I get the following error in ns-export-semantics semantic-pointcloud.
```
/workspace/FruitNeRF/FruitNeRF-ns-1.1.4/fruit_nerf/fruit_nerf_config.py:121: FutureWarning: above message coming from
  datamanager=FruitDataManagerConfig(
[15:40:37] Auto image downscale factor of 1                                                  fruitnerf_dataparser.py:320
Setting up training dataset...
Caching all 270 images.
Setting up evaluation dataset...
Caching all 30 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from fruit_nerf/2024-10-30_151923/nerfstudio_models/step-000029999.ckpt
Traceback (most recent call last):
  File "/usr/local/bin/ns-export-semantics", line 8, in <module>
    sys.exit(entrypoint())
  File "/workspace/FruitNeRF/FruitNeRF-ns-1.1.4/fruit_nerf/scripts/exporter.py", line 135, in entrypoint
    tyro.cli(Commands).main()
  File "/workspace/FruitNeRF/FruitNeRF-ns-1.1.4/fruit_nerf/scripts/exporter.py", line 94, in main
    pipeline.model.setup_inference(render_rgb=True, num_inference_samples=self.num_points_per_side)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FruitModel' object has no attribute 'setup_inference'
``` 

Do you know how to resolve this error?
Also, can you tell us how to create a more detailed environment in case of success?

**Comment by mitsuki05** [comment]
ns-1.1.4 didn't work out in the end, but I was able to create an environment for main, so I don't need it anymore.
